---

sudo: false
language: go
install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/golang/lint/golint
  - dep ensure -v
script:
  - go test -v --cover --short ./...
  - golint -set_exit_status github.com/aereal/go-magi
